.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/netsuite/Module.md, src/netsuite/netsuite_client.bal, src/netsuite/netsuite_constants.bal, src/netsuite/netsuite_error.bal, src/netsuite/netsuite_types.bal, src/netsuite/netsuite_utils.bal, src/netsuite/recordtypes/readable_records.bal, src/netsuite/recordtypes/sub_records.bal, src/netsuite/recordtypes/util_records.bal, src/netsuite/recordtypes/writable_records.bal, src/netsuite/tests/README.md, src/netsuite/tests/main_test.bal, src/netsuite/tests/test_utils.bal
> Connect to NetSuite from Ballerina
> Design doc : https://docs.google.com/document/d/1RZ6g6Do4nUAc5KRt3-61BqdwUt58h2cCDhVz6T_exfU/edit?usp=sharing
```ballerina
import ballerina/io;
import ballerinax/netsuite;
netsuite:Configuration nsConfig = {
baseUrl: "<BASE_URL>",
clientConfig: {
accessToken: "<ACCESS_TOKEN>"
}
};
netsuite:Client nsClient = new(nsConfig);
public function main() {
netsuite:Currency currency = {
name: "US Dollar",
symbol: "USD",
currencyPrecision: 2,
exchangeRate: 1.0
};
// Create the Currency record in NetSuite and populate passed-in record with id and defaults.
string|netsuite:Error created = nsClient->create(<@untainted> currency);
if created is netsuite:Error {
io:println("Error: " + created.detail()?.message.toString());
}
string id = <string> created; …
```
=> Introduce NetSuite Connector

.travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/netsuite/Module.md, src/netsuite/netsuite_client.bal, src/netsuite/netsuite_error.bal, src/netsuite/netsuite_utils.bal, src/netsuite/tests/README.md, src/netsuite/tests/main_test.bal, src/netsuite/tests/test_utils.bal
=> Migrate module to ballerina Swan Lake

Ballerina.lock, Ballerina.toml, README.md, src/netsuite/Module.md
=> Update readme sample syntax

.github/workflows/ci.yml, .github/workflows/release.yml, Ballerina.toml
Fix the CI github workflow build
=> Migration to SLP5- Github workflow build fix

.travis.yml, Ballerina.toml, Dependencies.toml, Package.md, Readme.md, client.bal, responseUtils.bal, salesOrder.bal
> Migrate connector to SLAlpha5
> Migration the Netsuite Connector to Ballerina Swan Lake Latest
- Unit tests 
> done
> done
> https://github.com/ballerina-platform/module-ballerinax-netsuite/tree/master/samples
> From SLAlpha4 to SLALpha5
> JDK 11, Ballerina Swan Lake Alpha5
=> Migration to Swan Lake Alpha5

Ballerina.toml, client.bal
> Fixing the issue with client initialization
- Unit tests 
> done
> done
> JDK 11, Ballerina Swan Lake Alpha5
=> Fix issue with client initialisation

.github/workflows/ci.yml, .github/workflows/release.yml, Invoice.bal, account.bal, accountTypes.bal, classification.bal, client.bal, constants.bal, contact.bal, currency.bal, customer.bal, entities.bal, responseUtils.bal, salesOrder.bal, salesTypes.bal, tests/test.bal
> Improve the connector UI experience in choreo.
Fixes https://github.com/wso2-enterprise/choreo/issues/4865
1] Updated display annotations
2] Added new test cases
3] Removed time module return type
4] updated the GitHub actions
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Alpha5
=> Improve the connector for better user experience at Choreo

netsuite/Invoice.bal, netsuite/account.bal, netsuite/accountTypes.bal, netsuite/classification.bal, netsuite/client.bal, netsuite/constants.bal, netsuite/contact.bal, netsuite/currency.bal, netsuite/customer.bal, netsuite/entities.bal, netsuite/responseUtils.bal, netsuite/salesOrder.bal, netsuite/salesTypes.bal, netsuite/tests/test.bal
> Improve the connector UI experience in choreo.
1] Updated display annotations
2] Added new test cases
3] Removed time module return type
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Beta1
=> Improving the connector for better user experince in choreo

Ballerina.toml, Invoice.bal, Package.md, Readme.md, account.bal, accountTypes.bal, client.bal, commonRecords.bal, commonUtils.bal, constants.bal, contact.bal, coreTypes.bal, customer.bal, enums.bal, responseUtils.bal, searchUtils.bal, streams.bal, tests/test.bal
> Fixes the issues of the search operations and improves the connector.
1. Added streams for search returns
2. Fix account record field issues
3. Add contact search operation
4. Added the facilities to search by transaction types eg: invoices/salesorders etc
5. Added test cases
- Unit tests 
> Done
> Done
> JDK 11, Ballerina SwanLake 5
=> Add streams return type  & new connector operations

README.md, netsuite/Invoice.bal, netsuite/Package.md, netsuite/account.bal, netsuite/accountTypes.bal, netsuite/client.bal, netsuite/commonRecords.bal, netsuite/commonUtils.bal, netsuite/constants.bal, netsuite/contact.bal, netsuite/coreTypes.bal, netsuite/customer.bal, netsuite/enums.bal, netsuite/responseUtils.bal, netsuite/searchUtils.bal, netsuite/streams.bal, netsuite/tests/test.bal
> Fixes the issues of the search operations and improves the connector.
1. Added streams for search returns
2. Fix account record field issues
3. Add contact search operation
4. Added the facilities to search by transaction types eg: invoices/sales orders etc
5. Added test cases
- Unit tests 
> Done
> Done
> JDK 11, Ballerina SLBeta1
=> Add streams return type & new connector operations

Package.md, Readme.md, accountTypes.bal, client.bal, commonRecords.bal, commonTypes.bal, constants.bal, entities.bal, reletionshipTypes.bal, salesTypes.bal, streams.bal, tests/test.bal
> Connector improvements in choreo view
=> Update display annotations and  configuration record base URL format

README.md, netsuite/Package.md, netsuite/accountTypes.bal, netsuite/client.bal, netsuite/commonRecords.bal, netsuite/commonTypes.bal, netsuite/constants.bal, netsuite/entities.bal, netsuite/reletionshipTypes.bal, netsuite/responseUtils.bal, netsuite/salesTypes.bal, netsuite/streams.bal, netsuite/tests/test.bal
> Connector improvements in choreo view
=> Update display annotations and configuration record netsuite base URL format

gradle.properties, netsuite/Dependencies.toml
Bump dependency versions to slbeta2
=> Bump dependency versions for Ballerina SLBeta2

README.md, netsuite/Module.md, netsuite/Package.md, netsuite/client.bal, netsuite/tests/test.bal
> $subject
Fixes https://github.com/wso2-enterprise/choreo/issues/6655
Ballerina Swan Lake beta 2
=> Update Netsuite documentation to the new format & Fix daily build

netsuite/tests/test.bal
> $subject
Fix daily build Failure
> Ballerina Swan Lake Beta2
=> Fix daily build Failure

gradle.properties, netsuite/Dependencies.toml
Bump dependency versions to stabilise the daily build in SLBeta3-SNAPSHOT
JDK 11
Ballerina SLBeta3
=> Bump dependency versions for Ballerina SLBeta3

netsuite/client.bal, netsuite/commonRecords.bal, netsuite/commonTypes.bal, netsuite/commonUtils.bal, netsuite/constants.bal, netsuite/contact.bal, netsuite/customer.bal, netsuite/entities.bal, netsuite/responseMapping.bal, netsuite/responseUtils.bal, netsuite/salesTypes.bal, netsuite/searchUtils.bal, netsuite/streams.bal, netsuite/tests/test.bal, netsuite/transcationRelatedTypes.bal, netsuite/vendor.bal, netsuite/vendorBill.bal
> $subject
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/25
Providing more record support through the connector
1. Implemented operations related to Vendor records
2. Implemented operations related to Vendor Bill records
3. Implemented  requests with custom xml bodies
4. Implemented search operation to vendor records
- Unit tests 
> Done
> Done
> Ballerina Swan Lake Beta3
> https://www.netsuite.com/portal/developers/resources/suitetalk-documentation.shtml
=> Add vendor/vendorBill record support

.github/workflows/ci.yml, .github/workflows/daily-build.yml, README.md
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
=> Update ballerina commands

netsuite/responseMapping.bal
Fixing daily build failure due to the changes of the Ballerina JSON-XML conversion
Fixes # (https://github.com/ballerina-platform/ballerina-extended-library/issues/143)
- Fixing Daily Build
* Ballerina Version: Swan Lake Beta4
* Operating System: Ubuntu
* Java SDK: JDK 11
=> Fix daily build failure on json[] casting

netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/responseMapping.bal
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/143
- Add fix done in https://github.com/ballerina-platform/module-ballerinax-netsuite/pull/56 to `slbeta3` branch
- Bump version to `2.0.1`
=> [SLBeta3] Fix typecast issue in responseMapping.bal

netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/responseMapping.bal
Reverts ballerina-platform/module-ballerinax-netsuite#57
=> Revert "[SLBeta3] Fix typecast issue in responseMapping.bal"

netsuite/Dependencies.toml, netsuite/client.bal, netsuite/responseMapping.bal, netsuite/tests/test.bal
Fixing Daily build failure due to ballerina nightly build package changes and removing warnings
- Daily build fixes
All tests pass
**Test Configuration**: 
* Ballerina Version: [Ballerina Latest Build](https://github.com/ballerina-platform/ballerina-distribution/actions/runs/1514606865) 
* Operating System: Ubuntu
* Java SDK: JAVA 11
=> Fix daily build

netsuite/client.bal
Modify icon as per new requirements 
- Removed .svg icon and added .png icon
- Icon size 200 x 200 px 
- Mention the icon in `Ballerina.toml` so that Ballerina central will render the connector icon
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/179
- Improved connector icon
N/A
N/A
=> Modify icon path at client.bal

README.md, gradle.properties, netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/Package.md
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
=> Prepare for 2.1.0 release with SLBeta3

netsuite/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
=> Re-generate Dependencies.toml with latest pack

gradle.properties, netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/Package.md
- Bump version to `2.2.0`
- Update Ballerina version to `2201.0.0` in Package.md 
- Regenerate Dependencies.toml with `2201.0.0`
- Add `distribution = "2201.0.0"` in Ballerina.toml
=> Prepare for 2.2.0 release with 2201.0.0

netsuite/tests/test.bal
The NetSuite test environment has been changed to a new NetSuite sandbox account with new configurations
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/273
- Changing the NetSuite test environment account.
All tests passed
* Ballerina Version: Swan Lake 2201.0.0
* Operating System:
* Java SDK: JAVA 11
=> Change netsuite test environment

netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/Package.md, netsuite/client.bal, netsuite/config-types.bal, netsuite/tests/test.bal
* Update ConnectionConfig record
* Bump connector version and ballerina version in Ballerina.toml
* Bump ballerina version in Package.md
* Update Dependencies.toml with Ballerina 2201.2.0
=> Alter ConnectionConfig record

netsuite/commonTypes.bal
=> Update http version

README.md, netsuite/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
=> Update Slack channel occurrences with Discord

netsuite/Ballerina.toml, netsuite/Invoice.bal, netsuite/account.bal, netsuite/accountTypes.bal, netsuite/client.bal, netsuite/commonRecords.bal, netsuite/commonUtils.bal, netsuite/coreTypes.bal, netsuite/enums.bal, netsuite/salesTypes.bal, netsuite/tests/test.bal
This is to improve the invoice support and to add itemgroup records for the connector
Fixes #https://github.com/ballerina-platform/ballerina-extended-library/issues/473
- Improved the netsuite invoice record CRUD operations with item-group record support
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version: Ballerina 2201.2.1 (Swan Lake Update 2)
* Operating System: Ubuntu
* Java SDK: JAVA 11
=> Add item group record support for invoices

netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
=> Update to Ballerina version 2201.3.0

netsuite/tests/test.bal
Disabled netsuite test as the test account is removed.
Fixes # (https://github.com/wso2-enterprise/choreo/issues/16555)
=> Disable netsuite tests

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, netsuite/Ballerina.toml, netsuite/Dependencies.toml, netsuite/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/483
=> Update to Ballerina version 2201.3.1

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, ballerina/Ballerina.toml, ballerina/Invoice.bal, ballerina/Package.md, ballerina/account.bal, ballerina/commonUtils.bal, ballerina/tests/test.bal, ballerina/vendorBill.bal
$subject.
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/576
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
=> Fix compatibility issues with 2201.8.0

.github/workflows/release.yml
Related to https://github.com/ballerina-platform/ballerina-extended-library/issues/589
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
=> [2201.8.x] Fix access token in release workflow
